### ISSUE TITLE
同时出现了四个编辑框

### ISSUE THREAD

**Issue by W-Mai** [zxhd863943427/siyuan-math-enhance#2]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/24841247/229408671-d313ac3e-8271-4b08-8991-904a2588faa7.png">

siyuan：2.8.2
插件：0.0.6
默认主题

**Comment by zxhd863943427** [comment]
请更新看看

**Comment by W-Mai** [comment]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/24841247/230362986-438c38bf-1a50-45ae-90c3-448324bed813.png">

感谢，问题已解决
